version: '3.8'
services:
  backend:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    ports:
      - "8000:8000"  # FastAPI or Streamlit
    volumes:
      - ../../data:/app/data
      - ../../storage:/app/storage
    environment:
      - LOG_SENTINEL_ENV=production
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ../../storage/clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=logs

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ../../storage/qdrant_data:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data:
